version: 0.2
env:
  variables:
    CHANGELIST: "-SNAPSHOT"
    AWS_ACCOUNT_ID: "518241560725"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - aws s3 sync s3://dev.tools.s3.devops.docbyte.cloud/ ~/tools/
      - chmod a+x -R ~/tools/
      - n 14
      - . ~/tools/prepEnv-new.sh
      - echo Build Started
  pre_build:
    commands:
      - . ~/tools/codebuild-gittools.sh
  build:
    commands:
      - VERSION=$(printf '%(%Y.%m.%d)T\n' -1)
      - if [ "$CODEBUILD_GIT_BRANCH" == "development" ];
        then
        CHANGELIST=-$CODEBUILD_BUILD_NUMBER;
        fi
      - VERSION=$(printf '%(%Y.%m.%d)T\n' -1)$CHANGELIST
      - MAVEN_ARGS=" -DskipTests -T4C -nsu -ntp -Dnuxeo.skip.enforcer=true"
      - mvn versions:set -DnewVersion=${VERSION} -DgenerateBackupPoms=false $MAVEN_ARGS
      - echo Build started on `date`
      - mvn clean compile install deploy $MAVEN_ARGS
      - echo Deployment done `date`
